{{- if not .Values.opnsense.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statedash.fullname" . }}
  labels: {{- include "statedash.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPNSENSE_KEY: {{ .Values.opnsense.key | quote }}
  OPNSENSE_SECRET: {{ .Values.opnsense.secret | quote }}
{{- end }}
